### ISSUE TITLE
Give this lib some love

### ISSUE THREAD

**Issue by umbynos** [arduino/go-win32-utils#2]
we should use `go.mod` in this lib, update the bindings and include some github actions workflow from the [assets repo]( https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/).

Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/sync-labels.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-dependencies-task.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-task.md
- [x] https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/test-go-task.md

**Comment by cmaglie** [comment]
Actually, the equivalent functions have been added in the golang runtime:

https://pkg.go.dev/golang.org/x/sys/windows#KnownFolderPath

We can use these functions and archive this repository.

**Comment by umbynos** [comment]
Nice! I'll create a task and close this one

**Comment by umbynos** [comment]
Related issues:
- https://github.com/arduino/arduino-cloud-cli/issues/110
- https://github.com/arduino/arduino-language-server/issues/134
- https://github.com/arduino/arduino-cli/issues/1835

After these have been completed, we can archive this library

**Comment by cmaglie** [comment]
It turns out that it is better to keep the repo after all:
* Updating the upstream projects requires splitting the code into architecture-specific variants, instead if we keep this repo we can do it here
* We are going to add more bindings (see #3 for example)

**Comment by MatteoPologruto** [comment]
Workflows added here:
- #5 
- #6 
- #7 
- #8 
- #9 
- #10 
- #12
